// <auto-generated />
using System;
using System.Collections.Generic;
using F1Trackr.Core.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1Trackr.Core.Migrations
{
    [DbContext(typeof(TrackrDbContext))]
    [Migration("20260221122219_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1Trackr.Core.Domain.Constructor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("LogoAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id", "Season");

                    b.ToTable("Constructors", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DriverNumber")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id", "Season");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Management.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Season")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Management.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConstructorPredictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<string>("DriverPredictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverRacePredictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreSnapshots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Management.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Race", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("Season");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("Round");

                    b.Property<string>("Circuit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FirstPracticeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrandPrixTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("QualifyingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SecondPracticeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SprintQualifyingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SprintTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ThirdPracticeTime")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Id", "F1Trackr.Core.Domain.Race.Id#RaceId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Round")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("Round");

                            b1.Property<string>("Season")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("Season");
                        });

                    b.HasKey("Season", "Round");

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.RaceResult", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("Season");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("Round");

                    b.Property<string>("ConstructorStandingsSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverStandingsSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualifyingResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SprintDriverResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RaceId", "F1Trackr.Core.Domain.RaceResult.RaceId#RaceId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Round")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("Round");

                            b1.Property<string>("Season")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("Season");
                        });

                    b.HasKey("Season", "Round");

                    b.ToTable("RaceResults", (string)null);
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Management.GroupMember", b =>
                {
                    b.HasOne("F1Trackr.Core.Domain.Management.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Trackr.Core.Domain.Management.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Trackr.Core.Domain.Management.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
